/**
 * @file ll_bitemporal_insert_select.sql
 * @ingroup bitemporal_dml
 * @brief Inserts a set of records into a bitemporal table using a SELECT query statement.
 * @param[in] p_table text Fully qualified bitemporal table name (`<schema>.<table_name>`).
 * @param[in] p_list_of_fields text Comma-separated column names to populate.
 * @param[in] p_select text SELECT query string providing source dataset values.
 * @param[in] p_effective temporal_relationships.timeperiod Business effective interval applied to all inserted records.
 * @param[in] p_asserted temporal_relationships.timeperiod System assertion interval applied to all inserted records.
 * @return integer Count of inserted records.
 * @pre Target table must be bitemporal and query in `p_select` must return columns matching `p_list_of_fields`.
 * @post Populates `p_table` with records generated by `p_select`.
 * @sa ll_bitemporal_insert, ll_bitemporal_update_select
 * @example
 * SELECT * FROM bitemporal_internal.ll_bitemporal_insert_select(
 *     'bitemp_tables.devices',
 *     'device_id, device_descr',
 *     $$SELECT device_id, device_descr FROM nontemporal.devices WHERE device_id BETWEEN 4 AND 10$$,
 *     '[now(), infinity)'::tstzrange,
 *     '[now(), infinity)'::tstzrange
 * );
 */
CREATE OR REPLACE FUNCTION bitemporal_internal.ll_bitemporal_insert_select(p_table text
,p_list_of_fields text
,p_select TEXT
,p_effective temporal_relationships.timeperiod 
,p_asserted temporal_relationships.timeperiod ) 
RETURNS INTEGER
AS
 $BODY$
DECLARE
v_rowcount INTEGER;
BEGIN
 EXECUTE format ($i$INSERT INTO %s (%s, effective, asserted )  
                 select a.*, %L,%L
                 from (%s) a RETURNING * $i$
                ,p_table
                ,p_list_of_fields
                ,p_effective
                ,p_asserted
                ,p_select) ;
     GET DIAGNOSTICS v_rowcount:=ROW_COUNT; 
     RETURN v_rowcount;         
     END;    
$BODY$ LANGUAGE plpgsql;
